### ISSUE TITLE
Pageformat change breaks retrieval code.

### ISSUE THREAD

**Issue by lapion** [janpascal/tv_grab_nl_java#18]
Hello Jan,

First of all I wish to thank you for maintaining this excellent code. 
However due to recent changes in the horizon.tv guide the guide cannot be grabbed anymore. Could you please check this ?

Lapion

**Comment by janpascal** [comment]
Hi Lapion,

It seems the internal Horizon channel numbers have changed. Could you please try reconfiguring the grabber, by running
$ tv_grab_nl_java --config-file /path/to/tv_grab_nl_java.xmltv --configure
After this, the xmltv ID's of the Horizon channels may have changed, please check your mythtv channel configuration. 

Could you let me know if this works for you?

Cheers

Jan-Pascal

**Comment by lapion** [comment]
Hi Jan-Pascal,

Thank you so much, that solved the problem.

There are still some minor problems I found in the verbose output of the the grabber when inserting the ratings. See the following pastebucket url:

http://pastebucket.com/82937

Lapion
