### ISSUE TITLE
Issues with ratings retrieval.

### ISSUE THREAD

**Issue by lapion** [janpascal/tv_grab_nl_java#21]
Hi Jan-Pascal,

There are still some minor problems I found in the verbose output of the the grabber when inserting the ratings. See the following pastebucket url:

http://pastebucket.com/82937

Lapion.

**Comment by janpascal** [comment]
Hi,

Those are messages from mythtv. They say that in the 'programrating' table in the mythconverg database, there is a key contraint violation. I'm not quite sure what causes it, maybe it has to do with the field lenghts of that table. I remember I changed them sometime, for the same reason.

Could you do paste the output of the SQL query 'show create table mythconverg.programrating'? If you don't know how, you can safely ignore the message. At worst, a few 'kijkwijzer' ratings will go missing.

**Comment by lapion** [comment]
Hi,
Okay thank you.

See: http://pastebucket.com/83026

**Comment by janpascal** [comment]
Okay, try this:
ALTER TABLE `programrating` CHANGE `rating` `rating` VARCHAR( 128 )

**Comment by lapion** [comment]
Won't this break the database incoherent ?

**Comment by janpascal** [comment]
I wouldn't think so, it just adjusts for the difference in space requirements between "PG-13" and "Afgeraden voor kinderen jonger dan 6 jaar, Geweld, Angst, Discriminatie". You may get some doubles for a while, but it will sort itself out.

**Comment by lapion** [comment]
Thank you very much for your help, keep up the good work.
