### ISSUE TITLE
tvvheadend compatible ?

### ISSUE THREAD

**Issue by jteeuw** [janpascal/tv_grab_nl_java#22]
Is tv_grab_nl tvheadend compatible, I get the folling error when I exucte ./tv_grab_nl.py --days 7 | nc -U /home/hts/.hts/tvheadend/epggrab/xmltv.sock

2015-04-07 13:29:14.964 xmltv: htsmsg_xml_deserialize error 
2015-04-07 13:29:14.964 xmltv: failed to read data

**Comment by janpascal** [comment]
Are you sure you're at the right product? You refer to a Python script,
while this project is about a Java program.

Anyway, the tv_grab_nl_java grabber is xmltv compatible. You will need
to first configure it. If you pipe stdout of the grabber directly into
some other process, you may want to use the --quiet flag to prevent
progress information to interfere with the xmltv output.

Cheers

Jan-Pascal

**Comment by janpascal** [comment]
Hi, any progress using my suggestion?

**Comment by janpascal** [comment]
Weird question, no follow-up, closing issue.

**Comment by jteeuw** [comment]
I was using the wrong grabber, everything works with the --quiet flag
