### ISSUE TITLE
NullPointerException when using ZiggoTV as a source

### ISSUE THREAD

**Issue by Rataplan626** [janpascal/tv_grab_nl_java#24]
Already addressed with tv_grab_nl_java-1.6.5-SNAPSHOT-dep.jar.

When grabbing EPG with ZiggoTV as source, a NullPointerException might occur when specific data is returned by ZiggoTV:

[Programme De Wereld Draait Door (VARA)@ Wed Sep 16 23:40:00 CEST 2015(null)]
{"last-modified":"2015-09-10 06:01:38","ProgramDetails":[{"id":null,"description":"","audio":0,"aspectRatio":null,"channelInHome":null,"channelOutOfHome":null,"channelOutOfCountry":null,"infoUrl":null,"ppeUrl":null,"rating":0,"ofRatings":0,"highDefinition":"false","rerun":"false","parentalGuidances":[1],"image":"","hashtag":[],"missedEpisodes":null}],"Program":[{"id":null,"channel":null,"title":"","startDate":"1969-12-31","startDateTime":"1970-01-01 00:00:00","endDateTime":"1970-01-01 00:00:00","genre":0,"outOfHome":null,"inHome":null,"outOfCountry":null,"series_key":"_"}]}
{"last-modified":"2015-09-10 06:01:38","ProgramDetails":[{"id":null,"description":"","audio":0,"aspectRatio":null,"channelInHome":null,"channelOutOfHome":null,"channelOutOfCountry":null,"infoUrl":null,"ppeUrl":null,"rating":0,"ofRatings":0,"highDefinition":"false","rerun":"false","parentalGuidances":[1],"image":"","hashtag":[],"missedEpisodes":null}],"Program":[{"id":null,"channel":null,"title":"","startDate":"1969-12-31","startDateTime":"1970-01-01 00:00:00","endDateTime":"1970-01-01 00:00:00","genre":0,"outOfHome":null,"inHome":null,"outOfCountry":null,"series_key":"_"}]}
Error in tv_grab_nl_java application
java.lang.NullPointerException
	at org.vanbest.xmltv.Config.translateCategory(Config.java:104)
	at org.vanbest.xmltv.ZiggoGids.fillDetails(ZiggoGids.java:199)
	at org.vanbest.xmltv.ZiggoGids.programmeFromJSON(ZiggoGids.java:285)
	at org.vanbest.xmltv.ZiggoGids.getProgrammes(ZiggoGids.java:323)
	at org.vanbest.xmltv.AbstractEPGSource.getProgrammes(AbstractEPGSource.java:48)
	at org.vanbest.xmltv.Main.fetchData(Main.java:136)
	at org.vanbest.xmltv.Main.run(Main.java:497)
	at org.vanbest.xmltv.Main.main(Main.java:532)

**Comment by janpascal** [comment]
Fixed in release 1.6.5
