### ISSUE TITLE
Horizon comedy central programming off by an unknown amount of time.

### ISSUE THREAD

**Issue by lapion** [janpascal/tv_grab_nl_java#26]
When you look online the programming of the comedy central is correct however the tvgravnljava downloaded data is of by an unknown amount of time.

**Comment by janpascal** [comment]
Hi, I've tried to reproduce this but couldn't. Would you please send me your tv_grab_nl_java configuration file, and indicate exactly which program (at which date and which time) is downloaded incorrectly?
