### ISSUE TITLE
Horizon broken

### ISSUE THREAD

**Issue by lapion** [janpascal/tv_grab_nl_java#27]
Hello,

Horizon has recently changed it's javascript, and now tv_grab_nl_java no longer gets any data.

**Comment by janpascal** [comment]
Yes, I've noticed. The URL of the javascript config changed. I will bring out a quick fix with the new URL. To fix it properly I need to parse the index HTML to find the configuration javascript URL, since it looks like is will change in the foreseeable future.

**Comment by janpascal** [comment]
Hi, could you check the 1.7.3 release to check if it works for you at the moment?

**Comment by lapion** [comment]
It seems to be working, at least on the surface.
